version: 2
jobs:
  build:
    working_directory: ~/build
    machine:
        image: circleci/classic:edge
    steps:
        - checkout:
             path: $CIRCLE_PROJECT_REPONAME
        - run:
             name: Build sample Application
             shell: /bin/bash
             command: |
                cd ~
                cp build/$CIRCLE_PROJECT_REPONAME/build.sh build
                cp build/$CIRCLE_PROJECT_REPONAME/config.sh build
                cp build/$CIRCLE_PROJECT_REPONAME/settings.xml build
                cd build
                chmod 777 ./build.sh
                ./build.sh

        - run:
             name: Push to docker Image Registry
             shell: /bin/bash
             command: |
                 cd ..        
                 docker login --username sairaghavarram --password sairaghavarram
                 docker push sairaghavarram/memoryloadergenerator
        - run:
                curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
                sudo chmod +x ./kubectl
                sudo mv ./kubectl /usr/local/bin/kubectl
                wget https://github.com/kubernetes/kops/releases/download/1.8.0/kops-linux-amd64
                sudo chmod +x kops-linux-amd64
                sudo mv kops-linux-amd64 /usr/local/bin/kops

                 

general:
  branches:
    only:
      - master
